[build]
  base = "."
  publish = "dashboard/dist"
  command = "cd dashboard && npm ci && npm run build && cd ../netlify && npm ci"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis","axios","xml2js","@netlify/blobs","openai"]

# Daily at 9:00 AM America/New_York (13:00 UTC outside DST) — adjust if needed
[[scheduled.functions]]
  name = "schedule-rss"
  cron = "0 13 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd dashboard && npm run dev"
  port = 5173
  publish = "dashboard/dist"